name: Build

on:
  push:
    branches: [ master ]

jobs:
  run_test:
    name: Run Test
    runs-on: ubuntu-latest
    container: golang:1.14
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: proxy_pool
        ports:
          - 3306:3306

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go env -w GO111MODULE=on && go mod tidy

      - name: Go Test
        run: go test ./... &&
              CGO_ENABLED=0 GOOS=linux go build -o main cmd/api/main.go &&
              CGO_ENABLED=0 GOOS=linux go build -o scheduler cmd/scheduler/main.go
        env:
          PROXY_POOL_CONFIG_FILE: ${{ github.workspace }}/config/conf.yaml
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: proxy_pool
          CI: github_action_ci

  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: release-lib/proxy-pool
          username: ${{ secrets.DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PWD }}
          registry: registry.cn-shanghai.aliyuncs.com
          dockerfile: Dockerfile
