name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_test:
    name: Run Test
    runs-on: ubuntu-latest
    container: golang:1.14
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: proxy_pool
        ports:
          - 3306:3306

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go env -w GO111MODULE=on && go mod tidy 

      - name: test
        run: go test ./...
        env:
          PROXY_POOL_CONFIG_FILE: /home/runner/work/proxy-pool/proxy-pool/config/conf.yaml
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: proxy_pool

  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: release-lib/proxy-pool
          username: ${{ secrets.DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PWD }}
          registry: registry.cn-shanghai.aliyuncs.com
          dockerfile: Dockerfile
